"use client";
import {useEffect,useState} from "react";
import JourneyIllustration from "./JourneyIllustration";
const stops=[
{n:'01',id:'what',label:'Idea submission',title:'It starts with your idea.',body:'Just an idea? Already building? Running a startup? You can apply at any stage. You do not need a big company name behind you.',note:'Tell us who you are, what you want to build and why it matters. Share a pitch video. A deck is optional.',links:[['Apply free','/apply']]},
{n:'02',id:'format',label:'Standing out',title:'From the crowd. To the shortlist.',body:'Tech founders, non-tech founders and HR reviewers will look at the submissions. The plan is to select 15 startups for the pitch stage.',note:'The rubric is being built with VC inputs. Applications received and final selection dates: TBA. These are planned places, not a claim that selection is complete.',links:[['See the selection process','/selection'],['Apply with your idea','/apply']]},
{n:'03',id:'event',label:'The roadshow',title:'Your idea. A live room.',body:'The shortlisted startups pitch in Bengaluru. Judges ask questions. VCs listen. The audience meets the people behind the ideas.',note:'24 October 2026. Judges, VC count, audience size, venue and pitch timings: TBA.',links:[['See the pitch-day plan','/event-details'],['Meet the judging track','/interest/judge'],['Join as a VC','/interest/vc'],['Get an audience pass','/register']]},
{n:'04',id:'travel',label:'Bengaluru → San Francisco',title:'Three teams. A bigger journey.',body:'The top three head from Bengaluru to the Startup World Cup event in San Francisco. SPL will provide visa recommendation letters and help you find funding for travel, tickets, stays and logistics.',note:'Travel funding and final arrangements will be worked out with selected teams. Visa decisions stay with the authorities. Event access and costs: TBA.',links:[['Read the founder pathway','/apply'],['Help back the trip','/interest/sponsor']]},
{n:'05',id:'world-cup',label:'Startup World Cup',title:'Bengaluru. On a global stage.',body:'Represent Bengaluru and your backers at a worldwide startup competition. Startup World Cup has a $1 million investment prize. It is an investment prize, not a cash grant from SPL.',note:'Final-round places depend on Startup World Cup selection. The top-three travel plan does not guarantee a finalist place or a prize.',links:[['Explore Startup World Cup','https://www.startupworldcup.io/'],['Meet Pegasus Tech Ventures','https://www.pegasustechventures.com/']]}
];
export default function StartupJourney(){const[active,setActive]=useState(0);useEffect(()=>{const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)setActive(Number(entry.target.dataset.step))},{rootMargin:'-20% 0px -45% 0px',threshold:0});document.querySelectorAll('.journey-stop').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);return <section id="journey" className="journey"><div className="wrap"><div className="journey-intro"><span className="eyebrow">Your road from Bengaluru to the world</span><h2>One idea.<br/><span className="hl">Five steps.</span></h2><p className="lede">Follow the road. See what happens next.</p></div><div className="journey-grid"><div className="road-sticky"><JourneyIllustration active={active}/></div><div className="journey-stops">{stops.map((stop,i)=><article id={stop.id} key={stop.n} data-step={i} className={'journey-stop '+(active===i?'is-active':'')}><div className="mobile-journey-art"><JourneyIllustration active={i}/></div><span className="journey-number">{stop.n}</span><span className="eyebrow">Step {i+1} · {stop.label}</span><h3>{stop.title}</h3><p className="journey-body">{stop.body}</p><p className="journey-note">{stop.note}</p><div className="cta-row">{stop.links.map(([label,href],j)=><a key={href} className={'btn '+(j===0?'btn-accent':'btn-ghost')} href={href} {...(href.startsWith('https')?{target:'_blank',rel:'noopener noreferrer'}:{})}>{label} →</a>)}</div>{i===1&&<aside className="audience-shortcut"><span className="eyebrow">↗ A second road · Audience track</span><h4>Come for the pitches. Join the quizzes.</h4><p>An audience quiz route is planned alongside the startup track. Rules, number of places and what the route unlocks: TBA. Buying an audience ticket does not buy a pitch or USA place.</p><a className="text-link" href="/register">Explore the audience route →</a></aside>}{i===4&&<><div className="journey-logos"><a href="https://www.startupworldcup.io/" target="_blank" rel="noopener noreferrer"><img src="/assets/swc/logo.png" alt="Startup World Cup"/></a><a href="https://www.pegasustechventures.com/" target="_blank" rel="noopener noreferrer"><img src="/assets/swc/pegasus.png" alt="Pegasus Tech Ventures"/></a></div><p className="journey-note">Partner VC lineup and logos: TBA. No unconfirmed backer is shown.</p></>}</article>)}</div></div></div></section>}
